name: Deploy AWS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make envfile for backend
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{ secrets.POSTGRES_URL}}
          directory: back-end/
          file_name: .env
          fail_on_empty: true
      - name: Make envfile for frontend
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{ secrets.REACT_APP_BASE_URL}}
          directory: front-end/
          file_name: .env
          fail_on_empty: true
      - name: Build   
        run: docker-compose build
      - name: run image
        run: docker-compose down && docker-compose up -d
